-- se ejecuta en sys en system
-- crear espacio fisico de trabajo
CREATE TABLESPACE PROCESOS 
DATAFILE 'D:\dataoracle\df_procesos.dbf' 
SIZE 100M EXTENT 
MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;

-- crear usuario
CREATE USER UPROCESOS
IDENTIFIED BY admin
DEFAULT TABLESPACE PROCESOS
TEMPORARY TABLESPACE TEMP
QUOTA UNLIMITED ON PROCESOS;

-- permisos
GRANT CONNECT TO UPROCESOS;
GRANT CREATE ANY TABLE TO UPROCESOS;